name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v6

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.41.6
        cache: true

    - name: Cache pub dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          .dart_tool/
        key: pub-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          pub-${{ runner.os }}-

    - name: Cache Flutter AAR
      id: cache-out
      uses: actions/cache@v4
      with:
        path: flutter/build/host/outputs/
        key: flutter-out-${{ hashFiles('flutter/pubspec.lock', 'flutter/lib/**/*.dart') }}

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
          
    - name: Cache Zig 0.15.2
      id: cache-zig-015
      uses: actions/cache@v4
      with:
        path: zig-x86_64-linux-0.15.2
        key: zig-0.15.2
        
    - name: Download Zig 0.15.2
      if: steps.cache-zig-015.outputs.cache-hit != 'true'
      run: |
        curl -OL https://ziglang.org/download/0.15.2/zig-x86_64-linux-0.15.2.tar.xz
        tar -xf zig-x86_64-linux-0.15.2.tar.xz

    - name: Build ncore
      run: |
          git clone https://github.com/FMAC-Team/ncore.git
          mkdir -p android/app/src/main/jniLibs/arm64-v8a/
          cd ncore
          ../zig-x86_64-linux-0.15.2/zig build \
            -Dtarget=aarch64-linux-android \
            -Doptimize=ReleaseSafe
           cp zig-out/lib/libncore.so ../android/app/src/main/jniLibs/arm64-v8a/
        
    - run: flutter pub get
 #   - run: flutter test
    - run: flutter build apk --release --target-platform android-arm64
  
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/*.apk

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
