name: Flutter CI with Rust (ncore)

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "android/**"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Cache Flutter Pub
        uses: actions/cache@v5
        with:
          path: ~/.pub-cache
          key: flutter-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: flutter-pub-

      - name: Cache Cargo
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ncore/target
          key: cargo-${{ runner.os }}-${{ hashFiles('ncore/Cargo.lock') }}
          restore-keys: cargo-${{ runner.os }}-

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          cache: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib

      - name: Build ncore
        run: |
          git clone https://github.com/nksu-crew/ncore.git
          cd ncore
          cargo install cargo-ndk
          cargo ndk -t arm64-v8a -o ../android/app/src/main/jniLibs/ build

      - name: Build APK
        run: |
          flutter pub get
          flutter build apk

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v6
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
